name: Payments API Release
on:
  push:
    branches: [main]
    paths:
      - "src/SourceSchemas/Payments/**"
      - "src/Defaults/**"
      - ".github/workflows/deploy-payments.yml"
      - ".github/workflows/deploy-source-schema.yml"
      - "Directory.Packages.props"
  workflow_dispatch: {}

jobs:
  deploy:
    uses: ./.github/workflows/deploy-source-schema.yml
    with:
      app_name: ccc-eu1-demo-ca-payments
      project_path: src/SourceSchemas/Payments
      container_port: 8080
      schema_file: src/SourceSchemas/Payments/schema.graphqls
      source_schema_name: payments-api
    secrets: inherit
