name: Shipping API Release
on:
  push:
    branches: [main]
    paths:
      - "src/SourceSchemas/Shipping/**"
      - "src/Defaults/**"
      - ".github/workflows/deploy-shipping.yml"
      - ".github/workflows/deploy-source-schema.yml"
      - "Directory.Packages.props"
  workflow_dispatch: {}

jobs:
  deploy:
    uses: ./.github/workflows/deploy-source-schema.yml
    with:
      app_name: ccc-eu1-demo-ca-shipping
      project_path: src/SourceSchemas/Shipping
      container_port: 8080
      schema_file: src/SourceSchemas/Shipping/schema.graphqls
      source_schema_name: shipping-api
    secrets: inherit
