name: Order API Release
on:
  push:
    branches: [main]
    paths:
      - "src/SourceSchemas/Order/**"
      - "src/Defaults/**"
      - ".github/workflows/deploy-order.yml"
      - ".github/workflows/deploy-source-schema.yml"
      - "Directory.Packages.props"
  workflow_dispatch: {}

jobs:
  deploy:
    uses: ./.github/workflows/deploy-source-schema.yml
    with:
      app_name: ccc-eu1-demo-ca-order
      project_path: src/SourceSchemas/Order
      container_port: 8080
      schema_file: src/SourceSchemas/Order/schema.graphqls
      source_schema_name: order-api
    secrets: inherit
